"""Seed the problems table with the initial 5 problems."""
import asyncio
from sqlalchemy import select
from app.database import engine, async_session
from app.models import Base, Problem


PROBLEMS = [
    {
        "problem_key": "p1",
        "type": "code",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": 'const name = "Alice"\nconst age = 25\nconsole.log(name)',
        "goal_content": 'const name = "Alice";\nconst age = 25;\nconsole.log(name);',
        "required_keys": ["ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "p2",
        "type": "code",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "function addd(a, b) {\n  returnn a + b;\n}",
        "goal_content": "function add(a, b) {\n  return a + b;\n}",
        "required_keys": ["ctrl_f", "ctrl_d"],
        "locale": "en",
    },
    {
        "problem_key": "p3",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": 'function greet(name) {\n  console.log("DEBUG");\n  return `Hello, ${name}!`;\n}',
        "goal_content": "function greet(name) {\n  return `Hello, ${name}!`;\n}",
        "required_keys": ["ctrl_n", "ctrl_a", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "p4",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": 'if  (x > 0)  {\n  console.log("positive")\n}',
        "goal_content": 'if (x > 0) {\n  console.log("positive");\n}',
        "required_keys": ["ctrl_f", "ctrl_d", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "p5",
        "type": "code",
        "difficulty": "hard",
        "category": "shortcut",
        "initial_content": 'function  calculate(x, y)  {\n  const result = x +  y;;\n  console.log("debug");\n  return result\n}',
        "goal_content": "function calculate(x, y) {\n  const result = x + y;\n  return result;\n}",
        "required_keys": ["ctrl_f", "ctrl_b", "ctrl_d", "ctrl_k", "ctrl_a", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    # --- Text problems ---
    {
        "problem_key": "t1",
        "type": "text",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "This is a testt message.\nPlease check it carefully.",
        "goal_content": "This is a test message.\nPlease check it carefully.",
        "required_keys": ["ctrl_f", "ctrl_d"],
        "locale": "en",
    },
    {
        "problem_key": "t2",
        "type": "text",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "The meeting is scheduled for Monday\nPlease confirm your attendance",
        "goal_content": "The meeting is scheduled for Monday.\nPlease confirm your attendance.",
        "required_keys": ["ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "t3",
        "type": "text",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "Dear Team,\nTODO: remove this line\nWe are pleased to announce the new policy.",
        "goal_content": "Dear Team,\nWe are pleased to announce the new policy.",
        "required_keys": ["ctrl_n", "ctrl_a", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "t4",
        "type": "text",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "The  quick  brown fox\njumps  over the  lazy dog",
        "goal_content": "The quick brown fox\njumps over the lazy dog.",
        "required_keys": ["ctrl_f", "ctrl_d", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "t5",
        "type": "text",
        "difficulty": "hard",
        "category": "shortcut",
        "initial_content": "Subject:  Project Update\nDRAFT - DO NOT SEND\nHi  everyone,\nThe deadline has been  extended to Friday\nBest regards",
        "goal_content": "Subject: Project Update\nHi everyone,\nThe deadline has been extended to Friday.\nBest regards.",
        "required_keys": ["ctrl_f", "ctrl_b", "ctrl_d", "ctrl_k", "ctrl_a", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "p6",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "import { useState, useEffect } from 'raect';\nimport Button from './components/Button';\nimport { api } from './utils/api';",
        "goal_content": "import { useState, useEffect } from 'react';\nimport { Button } from './components/Button';\nimport { api } from './utils/api';",
        "required_keys": ["ctrl_f", "ctrl_b", "ctrl_e", "ctrl_a"],
        "locale": "en",
    },
    {
        "problem_key": "p7",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "const UserCard = ({ name, age }) => {\n  return (\n    <div className=\"card\">\n      <h2>{name}</h2>\n      <p>Age: {age}</p>\n    </div>\n  );\n}",
        "goal_content": "const UserCard = ({ name, age, email }) => {\n  return (\n    <div className=\"user-card\">\n      <h2>{name}</h2>\n      <p>Age: {age}</p>\n      <p>Email: {email}</p>\n    </div>\n  );\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_e", "ctrl_a"],
        "locale": "en",
    },
    {
        "problem_key": "p8",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "async function fetchData() {\n  const data = await api.get('/users');\n  return data;\n}",
        "goal_content": "async function fetchData() {\n  try {\n    const data = await api.get('/users');\n    return data;\n  } catch (error) {\n    console.error(error);\n  }\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "p9",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "numbers = [1, 2, 3, 4, 5]\nsquared = []\nfor n in numbers:\n    squared.append(n * n)",
        "goal_content": "numbers = [1, 2, 3, 4, 5]\nsquared = [n * n for n in numbers]",
        "required_keys": ["ctrl_k", "ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p10",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "SELECT u.name, o.id\nFROM users u\nJOIN orders o ON u.id = o.user_id\nWHERE o.status = 'pending'",
        "goal_content": "SELECT u.name, o.id, o.total\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.status = 'completed'\nORDER BY o.created_at DESC",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_e", "ctrl_a", "ctrl_f", "ctrl_b"],
        "locale": "en",
    },
    {
        "problem_key": "p11",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": ".container {\n  display: block;\n  margin: 0 auto;\n  padding: 20px;\n}",
        "goal_content": ".container {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 20px;\n  padding: 20px;\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_k", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p12",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "{\n  \"name\": \"my-app\",\n  \"version\": \"1.0.0\",\n  \"debug\": true\n}",
        "goal_content": "{\n  \"name\": \"my-awesome-app\",\n  \"version\": \"1.0.1\",\n  \"private\": true,\n  \"scripts\": {\n    \"start\": \"node index.js\"\n  }\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p13",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "FROM node:14\nCOPY . .\nRUN npm install\nCMD [\"node\", \"app.js\"]",
        "goal_content": "FROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nCMD [\"node\", \"app.js\"]",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "p14",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "test('should add numbers', () => {\n  const result = add(1, 2);\n  expect(result).toBe(3);\n});",
        "goal_content": "test('should add positive numbers', () => {\n  const result = add(1, 2);\n  expect(result).toBe(3);\n  expect(add(2, 3)).toBe(5);\n});",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p15",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "class User {\n  constructor(name) {\n    this.name = name;\n  }\n  \n  save() {\n    db.save(this);\n  }\n}",
        "goal_content": "class User {\n  constructor(name, email) {\n    this.name = name;\n    this.email = email;\n  }\n  \n  async save() {\n    await db.save(this);\n    this.log('saved');\n  }\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_f", "ctrl_b"],
        "locale": "en",
    },
    {
        "problem_key": "t6",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Running List:\n- item 1\n* item 2\n- item 3",
        "goal_content": "Shopping List:\n- Apples\n- Bananas\n- Carrots",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_k", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t7",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Date: 2023/10/01\nAttendees: John, Mike\nDecisions:\n- None yet",
        "goal_content": "Date: 2023/12/01\nAttendees: John, Mike, Sarah\nDecisions:\n- Approved budget\n- Scheduled next meeting",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_e", "ctrl_a"],
        "locale": "en",
    },
    {
        "problem_key": "t8",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "Hey boss,\nI need day off tomorrow.\nThanks.",
        "goal_content": "Dear Manager,\nI would like to request a day off tomorrow for personal reasons.\nThank you for your understanding.\nSincerely,",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_k", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t9",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "株式会社〇〇\n田中様\nお疲れ様です。佐藤です。\n資料送ります。\nよろしく。",
        "goal_content": "株式会社〇〇\n営業部 田中様\nいつも大変お世話になっております。佐藤です。\n先日ご依頼のありました資料をお送りいたします。\nご確認のほど、よろしくお願い申し上げます。",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_f", "ctrl_b"],
        "locale": "ja",
    },
    {
        "problem_key": "t10",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "// fix this later\n// function to get data\n// returns null",
        "goal_content": "/**\n * Fetches user data from the API.\n * @returns {Promise<UserData>} The user object\n */",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_k", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t11",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Name: yamada taro\nTel: 09012345678\nAddr: tokyo-to minato-ku",
        "goal_content": "Name: Taro Yamada\nTel: 090-1234-5678\nAddress: Minato-ku, Tokyo",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t12",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Today was sunny.\nBut I stayed home.\nSo I was bored.",
        "goal_content": "Although today was sunny,\nI decided to stay home.\nConsequently, I felt quite bored.",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t13",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "Slide 1: Intro\n- we are good company\n- buy our product",
        "goal_content": "Slide 1: Introduction\n- Market Leaders in Innovation\n- Transforming the Industry\n- call to Action: Partner with Us",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "t14",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "1. boil water\n2. put noodles\n3. wait 3 mins\n4. eat",
        "goal_content": "1. Boil 500ml of water.\n2. Add noodles and spices.\n3. Simmer for 3 minutes.\n4. Serve hot and enjoy.",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t15",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "The sky is blue\nClouds are white\nBirds fly high",
        "goal_content": "The azure sky extends forever,\nDrifting white clouds pass by,\nSoaring birds reach for the sun.",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    # --- Japanese problems ---
    {
        "problem_key": "j1",
        "type": "text",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "こんにちはは。\n今日はいい天気ですね。",
        "goal_content": "こんにちは。\n今日はいい天気ですね。",
        "required_keys": ["ctrl_f", "ctrl_d"],
        "locale": "ja",
    },
    {
        "problem_key": "j2",
        "type": "text",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "お疲れ様です\n本日もよろしくお願いします",
        "goal_content": "お疲れ様です。\n本日もよろしくお願いします。",
        "required_keys": ["ctrl_e", "ctrl_n"],
        "locale": "ja",
    },
    {
        "problem_key": "j3",
        "type": "text",
        "difficulty": "easy",
        "category": "typing",
        "initial_content": "名前：山田\n年齢：25",
        "goal_content": "名前：山田太郎\n年齢：25歳",
        "required_keys": ["ctrl_e", "ctrl_n"],
        "locale": "ja",
    },
    {
        "problem_key": "j4",
        "type": "text",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "会議メモ\n【削除予定】テスト行\n次回は来週月曜日です。",
        "goal_content": "会議メモ\n次回は来週月曜日です。",
        "required_keys": ["ctrl_n", "ctrl_a", "ctrl_k"],
        "locale": "ja",
    },
    {
        "problem_key": "j5",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "件名：報告\n内容：完了",
        "goal_content": "件名：週次進捗報告\n内容：タスクAが完了しました。",
        "required_keys": ["ctrl_e", "ctrl_a", "ctrl_k", "ctrl_n"],
        "locale": "ja",
    },
    {
        "problem_key": "j6",
        "type": "text",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "明日の\u3000\u3000予定は\n10時から\u3000\u3000会議です",
        "goal_content": "明日の予定は\n10時から会議です。",
        "required_keys": ["ctrl_f", "ctrl_d", "ctrl_e", "ctrl_n"],
        "locale": "ja",
    },
    {
        "problem_key": "j7",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "買うもの：\n・りんご\n・バナナ",
        "goal_content": "週末の買い物リスト：\n・りんご 3個\n・バナナ 1房\n・牛乳 1本",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "ja",
    },
    {
        "problem_key": "j8",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "すみません、休みます。",
        "goal_content": "お忙しいところ恐れ入りますが、\n体調不良のため、本日お休みをいただけますでしょうか。\nご迷惑をおかけしますが、よろしくお願いいたします。",
        "required_keys": ["ctrl_a", "ctrl_k", "ctrl_e", "ctrl_n"],
        "locale": "ja",
    },
    {
        "problem_key": "j9",
        "type": "text",
        "difficulty": "hard",
        "category": "shortcut",
        "initial_content": "件名：\u3000\u3000打合せ\n日時：未定\n※下書き※\n参加者：田中、鈴木\n備考：\u3000\u3000なし",
        "goal_content": "件名：打合せ\n日時：2月20日 14:00\n参加者：田中、鈴木\n備考：なし",
        "required_keys": ["ctrl_f", "ctrl_b", "ctrl_d", "ctrl_k", "ctrl_a", "ctrl_e", "ctrl_n"],
        "locale": "ja",
    },
    {
        "problem_key": "j10",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "日記\n今日は散歩した。\n楽しかった。",
        "goal_content": "2月17日 日記\n今日は公園まで散歩した。\n桜がきれいで、とても楽しかった。",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_f"],
        "locale": "ja",
    },
    {
        "problem_key": "j11",
        "type": "text",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "東京都港区六本木\n1-2-33",
        "goal_content": "東京都港区六本木\n1-2-3",
        "required_keys": ["ctrl_n", "ctrl_e", "ctrl_h"],
        "locale": "ja",
    },
    {
        "problem_key": "j12",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "プロジェクト計画\n期間：1ヶ月\n目標：リリース",
        "goal_content": "プロジェクト計画書\n期間：2024年4月〜6月（3ヶ月）\n目標：ベータ版リリースおよびユーザーテスト完了",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "ja",
    },
    {
        "problem_key": "j13",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "レシピ：カレー\n材料：肉、野菜\n作り方：煮る",
        "goal_content": "レシピ：チキンカレー\n材料：鶏もも肉、玉ねぎ、にんじん、じゃがいも\n作り方：材料を炒めてから水を加え、30分煮込む。",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "ja",
    },
    {
        "problem_key": "j14",
        "type": "text",
        "difficulty": "easy",
        "category": "typing",
        "initial_content": "メモ\n牛乳を買う",
        "goal_content": "メモ\n帰りにスーパーで牛乳を買う。",
        "required_keys": ["ctrl_n", "ctrl_a", "ctrl_e"],
        "locale": "ja",
    },
    {
        "problem_key": "j15",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "自己紹介\n名前は田中です。\nエンジニアです。",
        "goal_content": "自己紹介\nはじめまして、田中太郎と申します。\nWebエンジニアとして5年間の経験があります。\n得意分野はフロントエンド開発です。",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "ja",
    },
    {
        "problem_key": "j16",
        "type": "text",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "エラーログ：\n[DEBUG] テスト出力\n[ERROR] 接続タイムアウト\n[DEBUG] 変数確認",
        "goal_content": "エラーログ：\n[ERROR] 接続タイムアウト",
        "required_keys": ["ctrl_n", "ctrl_a", "ctrl_k", "ctrl_p"],
        "locale": "ja",
    },
    # --- Mixed-language problems ---
    {
        "problem_key": "m1",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Name: Tanaka\nRole: Developer",
        "goal_content": "Name: 田中太郎 (Tanaka Taro)\nRole: Senior Developer",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "mixed",
    },
    {
        "problem_key": "m2",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "TODO: fix bug\nバグ修正",
        "goal_content": "TODO: fix login validation bug\nログインバリデーションのバグを修正する。\nPriority: High / 優先度：高",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "mixed",
    },
    {
        "problem_key": "m3",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "// Get user\nfunction getUser(id) {\n  return db.find(id);\n}",
        "goal_content": "// ユーザー情報を取得する\nfunction getUserById(id: string) {\n  return db.findById(id);\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k", "ctrl_f"],
        "locale": "mixed",
    },
    {
        "problem_key": "m4",
        "type": "text",
        "difficulty": "easy",
        "category": "typing",
        "initial_content": "Hello\nようこそ",
        "goal_content": "Hello, World!\nようこそ、世界へ！",
        "required_keys": ["ctrl_e", "ctrl_n", "ctrl_a"],
        "locale": "mixed",
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        for p in PROBLEMS:
            result = await session.execute(
                select(Problem).where(Problem.problem_key == p["problem_key"])
            )
            if result.scalar_one_or_none() is None:
                session.add(Problem(**p))
        await session.commit()
    print(f"Seeded {len(PROBLEMS)} problems.")


if __name__ == "__main__":
    asyncio.run(seed())
