"""Seed the problems table with the initial 5 problems."""
import asyncio
from sqlalchemy import select
from app.database import engine, async_session
from app.models import Base, Problem


PROBLEMS = [
    {
        "problem_key": "p1",
        "type": "code",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": 'const name = "Alice"\nconst age = 25\nconsole.log(name)',
        "goal_content": 'const name = "Alice";\nconst age = 25;\nconsole.log(name);',
        "required_keys": ["ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "p2",
        "type": "code",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "function addd(a, b) {\n  returnn a + b;\n}",
        "goal_content": "function add(a, b) {\n  return a + b;\n}",
        "required_keys": ["ctrl_f", "ctrl_d"],
        "locale": "en",
    },
    {
        "problem_key": "p3",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": 'function greet(name) {\n  console.log("DEBUG");\n  return `Hello, ${name}!`;\n}',
        "goal_content": "function greet(name) {\n  return `Hello, ${name}!`;\n}",
        "required_keys": ["ctrl_n", "ctrl_a", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "p4",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": 'if  (x > 0)  {\n  console.log("positive")\n}',
        "goal_content": 'if (x > 0) {\n  console.log("positive");\n}',
        "required_keys": ["ctrl_f", "ctrl_d", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "p5",
        "type": "code",
        "difficulty": "hard",
        "category": "shortcut",
        "initial_content": 'function  calculate(x, y)  {\n  const result = x +  y;;\n  console.log("debug");\n  return result\n}',
        "goal_content": "function calculate(x, y) {\n  const result = x + y;\n  return result;\n}",
        "required_keys": ["ctrl_f", "ctrl_b", "ctrl_d", "ctrl_k", "ctrl_a", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    # --- Text problems ---
    {
        "problem_key": "t1",
        "type": "text",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "This is a testt message.\nPlease check it carefully.",
        "goal_content": "This is a test message.\nPlease check it carefully.",
        "required_keys": ["ctrl_f", "ctrl_d"],
        "locale": "en",
    },
    {
        "problem_key": "t2",
        "type": "text",
        "difficulty": "easy",
        "category": "shortcut",
        "initial_content": "The meeting is scheduled for Monday\nPlease confirm your attendance",
        "goal_content": "The meeting is scheduled for Monday.\nPlease confirm your attendance.",
        "required_keys": ["ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "t3",
        "type": "text",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "Dear Team,\nTODO: remove this line\nWe are pleased to announce the new policy.",
        "goal_content": "Dear Team,\nWe are pleased to announce the new policy.",
        "required_keys": ["ctrl_n", "ctrl_a", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "t4",
        "type": "text",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "The  quick  brown fox\njumps  over the  lazy dog",
        "goal_content": "The quick brown fox\njumps over the lazy dog.",
        "required_keys": ["ctrl_f", "ctrl_d", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "t5",
        "type": "text",
        "difficulty": "hard",
        "category": "shortcut",
        "initial_content": "Subject:  Project Update\nDRAFT - DO NOT SEND\nHi  everyone,\nThe deadline has been  extended to Friday\nBest regards",
        "goal_content": "Subject: Project Update\nHi everyone,\nThe deadline has been extended to Friday.\nBest regards.",
        "required_keys": ["ctrl_f", "ctrl_b", "ctrl_d", "ctrl_k", "ctrl_a", "ctrl_e", "ctrl_n"],
        "locale": "en",
    },
    {
        "problem_key": "p6",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "import { useState, useEffect } from 'raect';\nimport Button from './components/Button';\nimport { api } from './utils/api';",
        "goal_content": "import { useState, useEffect } from 'react';\nimport { Button } from './components/Button';\nimport { api } from './utils/api';",
        "required_keys": ["ctrl_f", "ctrl_b", "ctrl_e", "ctrl_a"],
        "locale": "en",
    },
    {
        "problem_key": "p7",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "const UserCard = ({ name, age }) => {\n  return (\n    <div className=\"card\">\n      <h2>{name}</h2>\n      <p>Age: {age}</p>\n    </div>\n  );\n}",
        "goal_content": "const UserCard = ({ name, age, email }) => {\n  return (\n    <div className=\"user-card\">\n      <h2>{name}</h2>\n      <p>Age: {age}</p>\n      <p>Email: {email}</p>\n    </div>\n  );\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_e", "ctrl_a"],
        "locale": "en",
    },
    {
        "problem_key": "p8",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "async function fetchData() {\n  const data = await api.get('/users');\n  return data;\n}",
        "goal_content": "async function fetchData() {\n  try {\n    const data = await api.get('/users');\n    return data;\n  } catch (error) {\n    console.error(error);\n  }\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "p9",
        "type": "code",
        "difficulty": "medium",
        "category": "shortcut",
        "initial_content": "numbers = [1, 2, 3, 4, 5]\nsquared = []\nfor n in numbers:\n    squared.append(n * n)",
        "goal_content": "numbers = [1, 2, 3, 4, 5]\nsquared = [n * n for n in numbers]",
        "required_keys": ["ctrl_k", "ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p10",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "SELECT u.name, o.id\nFROM users u\nJOIN orders o ON u.id = o.user_id\nWHERE o.status = 'pending'",
        "goal_content": "SELECT u.name, o.id, o.total\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.status = 'completed'\nORDER BY o.created_at DESC",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_e", "ctrl_a", "ctrl_f", "ctrl_b"],
        "locale": "en",
    },
    {
        "problem_key": "p11",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": ".container {\n  display: block;\n  margin: 0 auto;\n  padding: 20px;\n}",
        "goal_content": ".container {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 20px;\n  padding: 20px;\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_k", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p12",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "{\n  \"name\": \"my-app\",\n  \"version\": \"1.0.0\",\n  \"debug\": true\n}",
        "goal_content": "{\n  \"name\": \"my-awesome-app\",\n  \"version\": \"1.0.1\",\n  \"private\": true,\n  \"scripts\": {\n    \"start\": \"node index.js\"\n  }\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p13",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "FROM node:14\nCOPY . .\nRUN npm install\nCMD [\"node\", \"app.js\"]",
        "goal_content": "FROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nCMD [\"node\", \"app.js\"]",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "p14",
        "type": "code",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "test('should add numbers', () => {\n  const result = add(1, 2);\n  expect(result).toBe(3);\n});",
        "goal_content": "test('should add positive numbers', () => {\n  const result = add(1, 2);\n  expect(result).toBe(3);\n  expect(add(2, 3)).toBe(5);\n});",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "p15",
        "type": "code",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "class User {\n  constructor(name) {\n    this.name = name;\n  }\n  \n  save() {\n    db.save(this);\n  }\n}",
        "goal_content": "class User {\n  constructor(name, email) {\n    this.name = name;\n    this.email = email;\n  }\n  \n  async save() {\n    await db.save(this);\n    this.log('saved');\n  }\n}",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_f", "ctrl_b"],
        "locale": "en",
    },
    {
        "problem_key": "t6",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Running List:\n- item 1\n* item 2\n- item 3",
        "goal_content": "Shopping List:\n- Apples\n- Bananas\n- Carrots",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_k", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t7",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Date: 2023/10/01\nAttendees: John, Mike\nDecisions:\n- None yet",
        "goal_content": "Date: 2023/12/01\nAttendees: John, Mike, Sarah\nDecisions:\n- Approved budget\n- Scheduled next meeting",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_e", "ctrl_a"],
        "locale": "en",
    },
    {
        "problem_key": "t8",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "Hey boss,\nI need day off tomorrow.\nThanks.",
        "goal_content": "Dear Manager,\nI would like to request a day off tomorrow for personal reasons.\nThank you for your understanding.\nSincerely,",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_k", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t9",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "株式会社〇〇\n田中様\nお疲れ様です。佐藤です。\n資料送ります。\nよろしく。",
        "goal_content": "株式会社〇〇\n営業部 田中様\nいつも大変お世話になっております。佐藤です。\n先日ご依頼のありました資料をお送りいたします。\nご確認のほど、よろしくお願い申し上げます。",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_f", "ctrl_b"],
        "locale": "ja",
    },
    {
        "problem_key": "t10",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "// fix this later\n// function to get data\n// returns null",
        "goal_content": "/**\n * Fetches user data from the API.\n * @returns {Promise<UserData>} The user object\n */",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_k", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t11",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Name: yamada taro\nTel: 09012345678\nAddr: tokyo-to minato-ku",
        "goal_content": "Name: Taro Yamada\nTel: 090-1234-5678\nAddress: Minato-ku, Tokyo",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t12",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "Today was sunny.\nBut I stayed home.\nSo I was bored.",
        "goal_content": "Although today was sunny,\nI decided to stay home.\nConsequently, I felt quite bored.",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t13",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "Slide 1: Intro\n- we are good company\n- buy our product",
        "goal_content": "Slide 1: Introduction\n- Market Leaders in Innovation\n- Transforming the Industry\n- call to Action: Partner with Us",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e", "ctrl_k"],
        "locale": "en",
    },
    {
        "problem_key": "t14",
        "type": "text",
        "difficulty": "medium",
        "category": "typing",
        "initial_content": "1. boil water\n2. put noodles\n3. wait 3 mins\n4. eat",
        "goal_content": "1. Boil 500ml of water.\n2. Add noodles and spices.\n3. Simmer for 3 minutes.\n4. Serve hot and enjoy.",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_f", "ctrl_b", "ctrl_e"],
        "locale": "en",
    },
    {
        "problem_key": "t15",
        "type": "text",
        "difficulty": "hard",
        "category": "typing",
        "initial_content": "The sky is blue\nClouds are white\nBirds fly high",
        "goal_content": "The azure sky extends forever,\nDrifting white clouds pass by,\nSoaring birds reach for the sun.",
        "required_keys": ["ctrl_n", "ctrl_p", "ctrl_a", "ctrl_e"],
        "locale": "en",
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        for p in PROBLEMS:
            result = await session.execute(
                select(Problem).where(Problem.problem_key == p["problem_key"])
            )
            if result.scalar_one_or_none() is None:
                session.add(Problem(**p))
        await session.commit()
    print(f"Seeded {len(PROBLEMS)} problems.")


if __name__ == "__main__":
    asyncio.run(seed())
